# Generated by Django 4.1.5 on 2023-03-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_category_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casher.category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='casher.product'),
        ),
    ]
