# Generated by Django 4.1.5 on 2023-03-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casher', '0002_alter_stock_stock_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
